### ISSUE TITLE
Unable to install zig-lang on Alpine Linux

### ISSUE THREAD

**Issue by claudiunv** [cheetah/asdf-zig#12]
I had no problems on installing the **asdf-zig** plugin except I've got the following error on installing any version of zig:

```
$ asdf install zig 0.11.0
mktemp: Invalid argument
Downloading https://ziglang.org/download/0.11.0/zig-linux-x86_64-0.11.0.tar.xz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to open the file /archive: Permission denied
  0 42.8M    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (23) Failure writing output to destination
```

Investigating more on the issue, the problem is the **busybox**'s flavour of `mktemp`. The fix is simple, replace `asdf-zig.XXXX` with `asdf-zig.XXXXXX` from the `asdf-zig/tree/master/bin/install` script. This change works fine on another machine with Ubuntu Linux inside.

**Comment by cheetah** [comment]
Thank you
