### ISSUE TITLE
support for macos-aarch64

### ISSUE THREAD

**Issue by bzoop** [cheetah/asdf-zig#4]
Looks like tarballs are now being created for master branch, just not shown on the downloads page quiet yet.
ref: https://github.com/ziglang/zig/issues/8149

**Comment by bzoop** [comment]
Seems like this is the only changed that will be needed?
```
diff --git a/bin/utils b/bin/utils
index b840929..6f782f8 100755
--- a/bin/utils
+++ b/bin/utils
@@ -27,7 +27,7 @@ get_arch() {
     x86_64|amd64)
       arch="x86_64"
       ;;
-    aarch64)
+    aarch64|arm64)
       arch="aarch64"
       ;;
     *)
```

**Comment by cheetah** [comment]
Thank you, that's definitely reasonable change, but unfortunately there is still no aarch64 tarball in https://ziglang.org/download/index.json

Just updated architecture detection with yours patch, so waiting for zig's download page update

**Comment by bzoop** [comment]
Looks like macos-aarch64 is now available on the downloads page. 🎉

```
~% uname -sm
Darwin arm64
~% asdf install zig master       
Downloading https://ziglang.org/builds/zig-macos-aarch64-0.8.0-dev.1811+cab1d5c1a.tar.xz...
~% asdf global zig master
~[1]% zig version
0.8.0-dev.1811+cab1d5c1a
```
