### ISSUE TITLE
Failure to detect latest master release?

### ISSUE THREAD

**Issue by achou11** [cheetah/asdf-zig#5]
Attempting to upgrade using `asdf install zig master` but I just get a message saying that `zig master is already installed`. As of today, the latest available version is `0.10.0-dev.2977+7d2e14267` while I'm currently on `0.10.0-dev.237+ada8e1713`. My understanding is that this plugin uses the official zig repo to check which version is available as opposed to resolving some other  hosted third-party platform that needs updating (\*cough\* homebrew \*cough\*). Is it reasonable to suggest that there's something unexpected happening in the version detection?

**Comment by cheetah** [comment]
Hi, plugin uses official zig website as a source, but all master revisions treats as the same version labeled `master`

So you just need to
```
asdf uninstall zig master
asdf install zig master
```
to get latest master build on the moment
